spring:
  application:
    name: spring_security_cognito_240424
  security:
    oauth2:
      client:
        registration:
          cognito:
            clientId: ${spring.security.oauth2.client.registration.cognito.clientId}
            clientSecret: ${spring.security.oauth2.client.registration.cognito.clientSecret}
            scope: openid
            redirect-uri: http://localhost:8080/login/oauth2/code/cognito
            clientName: vigor-bat-day
        provider:
          cognito:
            issuerUri: ${spring.security.oauth2.client.provider.cognito.issuerUri}
            user-name-attribute: username
  datasource:
    url: jdbc:mysql://localhost:3306/tasks_cognito
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
aws:
  cognito:
    poolId: ${aws.cognito.poolId}
    registration:
      clientId: ${aws.cognito.registration.clientId}